apiVersion: v1
kind: Service
metadata:
  namespace: hulkbuster
  name: nginx-test-svc
spec:
  type: NodePort
  selector:
    app: nginx
  externalIPs:
  - 192.168.1.240 
  ports:
    - port: 80
      nodePort: 30300
      targetPort: 80
