apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: hulkbuster
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx-cont2
        image: nginx:1.14.2
        ports:
        - containerPort: 80
