apiVersion: v1
kind: Service
metadata:
  namespace: asgard
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx2
  externalIPs:
  - 192.168.1.240 
  ports:
    - port: 80
      nodePort: 32222
      targetPort: 80
